/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.0.0.24.1
    Soft IP Version: 1.0.2
    2021 12 02 20:24:53
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module player (rd_clk_i, rst_i, rd_en_i, rd_clk_en_i, rd_addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rst_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [4:0]  rd_addr_i;
    output  [31:0]  rd_data_o;
endmodule